version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/apps/web/ssl:/etc/nginx/certs:ro"
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/apps/web/ssl:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mariadb:/bitnami
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
  ghost:
    image: 'bitnami/ghost:latest'
    container_name: ghost
    expose:
      - '2368'
    volumes:
      - '/var/lib/ghost:/bitnami'
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=${WEBHOST},www.${WEBHOST}
      - LETSENCRYPT_HOST=${WEBHOST},www.${WEBHOST}
      - LETSENCRYPT_EMAIL={MYEMAIL}
      - GHOST_HOST=www.${WEBHOST}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}